Repository tweag/nixpkgs-graph-explorer, pull requests merged in 2023-05, with the labels that each got.

#85 Delete etl directory
  etl/Dockerfile
  etl/README.md
  etl/etl.py
  etl/example_query.py
  etl/nixpkgs-graph.nix
  etl/requirements.txt
  etl/test-requirements.txt
  etl/test_spec.py
Labels: component:etl

#96 Improve READMEs
  .prettierignore
  README.md
  api/README.md
  core/README.md
  flake.nix
  web/README.md
Labels: priority:high, documentation

#102 CI: add nightly pipeline, that runs extraction
  .github/workflows/nightly.yml
Labels: ci

#107 Improve READMEs
  README.md
  api/README.md
Labels: documentation
