Repository tweag/nixpkgs-graph-explorer, pull requests merged in 2023-06, with the labels that each got.

#114 Delete nightly pipeline, superseded by regular CI since PR #108
  .github/workflows/nightly.yml
Labels: ci

#104 Display details for selected node
  web/src/app-main.ts
  web/src/graph-viewer.ts
Labels: component:ui

#117 Update explorer.core CLI, update READMEs
  README.md
  api/README.md
  api/pyproject.toml
  core/README.md
  core/derivation.schema.json
  core/explorer/core/__main__.py
  core/explorer/extract/cli.py
  core/nixpkgs-graph.schema.json
Labels: component:etl, documentation

#119 Batch gremlin traversals
  api/explorer/api/graph.py
  api/explorer/api/ingest.py
  api/tests/conftest.py
  api/tests/test_graph.py
Labels: component:etl, component:backend

#118 Add Dockerfile for ETL command execution in a Docker container and update Readme
  README.md
  api/poetry.lock
  api/pyproject.toml
  docker/etl/Dockerfile
Labels: component:etl

#121 Remove query editor
  web/src/app-main.ts
  web/src/code-editor.ts
Labels: component:ui

#123 Fix Nix search display: scroll
  web/src/app-main.ts
  web/src/graph-viewer.ts
  web/src/nix-search.ts
Labels: component:ui

#126 ui: no search when the input is empty
  web/src/nix-search.ts
Labels: component:ui

#125 Add structured logging to ingestion
  api/explorer/api/ingest.py
  docker/sqlg/docker-entrypoint.sh
  docker/sqlg/gremlin-server.yaml
Labels: component:etl
