Repository tweag/nixpkgs-graph-explorer, pull requests merged in 2023-04, with the labels that each got.

#56 Add core package with data model and JSON schema
  core/README.md
  core/explorer/core/__init__.py
  core/explorer/core/__main__.py
  core/explorer/core/model.py
  core/nixpkgs-graph.schema.json
  core/poetry.lock
  core/pyproject.toml
  core/tox.ini
Labels: component:etl, component:backend

#63 Write About
  web/src/app-main.ts
Labels: component:ui

#64 style loader
  web/package.json
  web/src/app-main.ts
  web/src/nix-search.ts
Labels: component:ui

#57 Add an extract data CLI to the core package
  core/README.md
  core/extract_data/cli/__init__.py
  core/extract_data/cli/__main__.py
  core/extract_data/cli/nixpkgs-graph.nix
  core/pyproject.toml
Labels: component:etl

#59 Migrate data ingestion logic to api package
  .dockerignore
  README.md
  api/.env.dev
  api/Dockerfile
  api/README.md
  api/docker-compose.prod.yml
  api/docker-compose.yml
  api/explorer/api/__init__.py
  api/explorer/api/graph.py
  api/explorer/api/ingest.py
  api/explorer/api/queries/__init__.py
  api/explorer/api/queries/cytoscape.py
  api/explorer/api/queries/packages.py
  api/explorer/api/queries/pagination.py
  api/explorer/api/queries/query.py
  api/explorer/api/queries/test/test_query.py
  api/explorer/api/test/test_graph.py
  api/explorer/api/test/test_ingest.py
  api/explorer/api/test/test_packages.py
  api/poetry.lock
  api/pyproject.toml
  core/explorer/core/model.py
  docker-compose.dev.yaml
  docker-compose.yaml
Labels: component:etl, component:backend

#69 Update configuration to be more compatible with cloud deployments
  api/explorer/api/__init__.py
  docker-compose.yaml
  docker/sqlg/gremlin-server.yaml
Labels: component:backend, component:infra

#74 Add custom gremlin transport
  api/explorer/api/__init__.py
  api/explorer/api/gremlin.py
  api/explorer/api/ingest.py
  api/explorer/api/queries/test/test_query.py
  api/explorer/api/test/test_graph.py
  api/explorer/api/test/test_gremlin.py
  api/explorer/api/test/test_ingest.py
  api/explorer/api/test/test_packages.py
  api/poetry.lock
  api/pyproject.toml
Labels: component:backend

#80 Recursively collect input derivations
  core/README.md
  core/explorer/extract/__init__.py
  core/explorer/extract/__main__.py
  core/explorer/extract/nixpkgs-graph.nix
  core/extract_data/cli/__main__.py
  core/extract_data/cli/nixpkgs-graph.nix
  core/pyproject.toml
Labels: component:etl
